[build]
  command = "yarn deploy"
  publish = "out"
  base = "."
  functions = "./functions"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "Chec Public Key (under Setup > Developer)"
