[build]
  command = "yarn deploy"
  publish = "out"
  base = "."
  functions = "./functions"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "pk_18450a139fb2b642baab2dd8899d3415142e2a9c91875"
